# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20160823_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='M4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='m3',
            old_name='f2',
            new_name='f',
        ),
    ]
