# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 16:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20160823_1616'),
    ]

    operations = [
        migrations.DeleteModel(
            name='M4',
        ),
    ]
