# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_delete_m4'),
    ]

    operations = [
        migrations.CreateModel(
            name='M1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f', models.IntegerField()),
            ],
        ),
    ]
