# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 16:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_m1'),
        ('app', '0010_m3'),
    ]

    operations = [
    ]
