# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 09:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_merge_20160823_1647'),
    ]

    operations = [
        migrations.DeleteModel(
            name='M3',
        ),
    ]
