# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 12:43
from __future__ import unicode_literals

import app.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_custom'),
    ]

    operations = [
        migrations.AddField(
            model_name='m1',
            name='csf',
            field=app.models.CommaSepField(default=1),
            preserve_default=False,
        ),
    ]
